/* MOTOR MADRE - navegación, puntaje, Supabase y certificado. */
(()=>{"use strict";
const $=id=>document.getElementById(id),questionnaires=window.QUESTIONNAIRE_DATA||[],intros=window.INTRO_CONTENT||{},content=window.OPINION_CONTENT||{},config=window.APP_CONFIG||{},screens=[...document.querySelectorAll(".screen")];
const state={masterclass:null,intro:null,questionIndex:0,score:0,answers:[],questionStart:0,times:{},surveyBlock:"demographics",surveyIndex:0,opinion:{},participant:null,responseId:null,started:new Date().toISOString(),finished:null,certificateCanvas:null};
const blocks={demographics:{label:"Datos y contexto",questions:()=>content.demographics||[],next:"likert",intro:""},likert:{label:"Tu opinión sobre el material",questions:()=>content.likert||[],next:"projection",intro:"Por favor, también contanos muy rápidamente tu opinión sobre el video que viste. <strong>Tu certificado está casi listo.</strong>"},projection:{label:"Proyección didáctica",questions:()=>visibleProjection(),next:"comment",intro:"¡Las últimas 4 preguntitas, ya estamos generando el pdf de tu certificado!"},comment:{label:"Para terminar",questions:()=>[content.comment],next:"data",intro:""}};
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function inferSlug(){const query=new URLSearchParams(location.search).get("clase"),file=location.pathname.split("/").pop().replace(/\.html$/i,"").toLowerCase(),authorPages={masterclassgg:"oppenheimer",masterclassjc:"adn",masterclasstl:"medir",masterclassnc:"biodiversidad"};return questionnaires.some(x=>x.slug===query)?query:questionnaires.some(x=>x.slug===file)?file:authorPages[file]||"oppenheimer"}
function show(id,progress,label){screens.forEach(screen=>screen.classList.toggle("active",screen.id===id));document.body.classList.toggle("in-intro",id==="screen-intro");$("progress-bar").style.width=`${progress}%`;$("step-label").textContent=label||"";scrollTo({top:0,behavior:"smooth"})}
function initialize(){state.masterclass=questionnaires.find(x=>x.slug===inferSlug());state.intro=intros[state.masterclass?.slug];if(!state.masterclass||!state.intro){document.body.innerHTML='<main class="fatal-error">Falta la configuración de esta masterclass.</main>';return}document.title=`${state.masterclass.title} · Fenomenautas`;$("intro-title").textContent=state.intro.portadaTitulo||state.masterclass.title;$("intro-subtitle").textContent=state.intro.portadaSubtitulo||"";$("intro-subtitle").hidden=!state.intro.portadaSubtitulo;$("intro-copy").textContent=state.intro.portadaTexto;$("eval-intro-title").textContent=state.intro.evaluacionTitulo;$("eval-intro-copy").textContent=state.intro.evaluacionTexto;$("eval-intro-objective").textContent=state.intro.evaluacionObjetivo;show("screen-intro",0,"")}
function shuffled(options){const unknown=options.find(x=>/no sé/i.test(x.text)),regular=options.filter(x=>x!==unknown);for(let i=regular.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[regular[i],regular[j]]=[regular[j],regular[i]]}return unknown?[...regular,unknown]:regular}
function startQuiz(){state.questionIndex=0;state.score=0;state.answers=[];state.times={};renderQuestion();show("screen-quiz",6,"Veamos cuánto aprendiste")}
function renderQuestion(){const question=state.masterclass.questions[state.questionIndex],feedback=$("feedback"),list=$("options-list");state.questionStart=performance.now();$("question-counter").textContent=`Pregunta ${state.questionIndex+1} de ${state.masterclass.questions.length}`;$("question-text").textContent=question.prompt;$("quiz-multi-hint").hidden=true;$("question-warning").hidden=true;$("question-next").disabled=true;$("question-next").textContent=state.questionIndex===state.masterclass.questions.length-1?"Continuar →":"Siguiente →";feedback.hidden=true;feedback.className="feedback";feedback.innerHTML="";list.innerHTML="";delete list.dataset.key;delete list.dataset.text;
shuffled(question.options).forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="option-btn";button.dataset.key=option.key;button.innerHTML=`<span class="option-letter">${String.fromCharCode(65+index)}</span><span>${esc(option.text)}</span>`;button.onclick=()=>selectEvaluation(question,option,button);list.appendChild(button)});$("progress-bar").style.width=`${6+Math.round(state.questionIndex/state.masterclass.questions.length*34)}%`}
function selectEvaluation(question,option,button){const list=$("options-list");if(list.dataset.key)return;const correct=question.scored?option.key===question.correct:null;[...list.children].forEach(item=>{item.disabled=true;if(question.scored&&item.dataset.key===question.correct)item.classList.add("correct")});button.classList.add("selected");if(question.scored&&!correct)button.classList.add("wrong");list.dataset.key=option.key;list.dataset.text=option.text;const feedback=$("feedback");feedback.classList.add(question.scored?(correct?"good":"bad"):"neutral");feedback.innerHTML=question.scored?`<strong>${correct?"¡Correcto!":"Respuesta incorrecta"}</strong>${esc(question.feedback||"")}`:'<strong>¡Gracias!</strong> Tu respuesta fue registrada. Esta pregunta no suma ni resta puntos.';feedback.hidden=false;$("question-next").disabled=false}
function nextQuestion(){const list=$("options-list"),key=list.dataset.key;if(!key){$("question-warning").hidden=false;return}const question=state.masterclass.questions[state.questionIndex],correct=question.scored?key===question.correct:null;if(correct)state.score++;state.times[`p${state.questionIndex+1}`]=Math.round((performance.now()-state.questionStart)/100)/10;state.answers.push({number:question.number,prompt:question.prompt,selectedOptionKey:key,selectedText:list.dataset.text,correctOptionKey:question.correct,isCorrect:correct,feedback:question.feedback,scored:question.scored});state.questionIndex++;if(state.questionIndex<state.masterclass.questions.length){renderQuestion();return}show("screen-transition",42,"Tu opinión")}
function visibleProjection(){const all=content.projection||[],use=state.opinion.proy_usar||"",positive=use.startsWith("Sí, definitivamente")||use.startsWith("Sí, es probable");return all.filter(q=>!q.conditional||positive)}
function startSurvey(){state.surveyBlock="demographics";state.surveyIndex=0;renderSurvey();show("screen-survey",44,blocks.demographics.label)}
function blockProgress(key,index,total){const ranges={demographics:[44,58],likert:[58,68],projection:[68,79],comment:[79,82]},range=ranges[key];return range[0]+Math.round(index/Math.max(total,1)*(range[1]-range[0]))}
function renderSurvey(){const block=blocks[state.surveyBlock],questions=block.questions(),question=questions[state.surveyIndex],control=$("survey-control"),intro=$("survey-block-intro");$("step-label").textContent=block.label;$("survey-counter").textContent=`Pregunta ${state.surveyIndex+1} de ${questions.length}`;$("survey-title").innerHTML=question.title;$("survey-error").hidden=true;intro.innerHTML=block.intro;intro.hidden=!block.intro;$("progress-bar").style.width=`${blockProgress(state.surveyBlock,state.surveyIndex,questions.length)}%`;
if(question.textarea){control.innerHTML=`<textarea id="survey-value" placeholder="${esc(question.placeholder)}"></textarea>`;return}if(question.likert){control.innerHTML=`<div class="likert-labels"><span>Totalmente en desacuerdo</span><span>Totalmente de acuerdo</span></div><div class="likert-scale">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="survey" value="${n}"><span>${n}</span></label>`).join("")}</div>`;return}control.innerHTML=`${question.multiple?'<div class="multi-hint">Seleccioná todas las opciones que correspondan.</div>':""}<div class="survey-options">${question.options.map((option,index)=>`<label class="survey-option"><input type="${question.multiple?"checkbox":"radio"}" name="survey" value="${esc(option)}"><span class="option-letter">${question.multiple?"+":String.fromCharCode(65+index)}</span><span>${esc(option)}</span></label>`).join("")}</div>`;if(question.multiple&&question.exclusive)control.querySelectorAll("input").forEach(input=>input.addEventListener("change",()=>enforceExclusive(question,input)))}
function enforceExclusive(question,input){if(!input.checked)return;const inputs=[...document.querySelectorAll('#survey-control input')],isExclusive=question.exclusive.includes(input.value);inputs.forEach(other=>{if(other!==input&&(isExclusive||question.exclusive.includes(other.value)))other.checked=false})}
function submitSurvey(event){event.preventDefault();const block=blocks[state.surveyBlock],questions=block.questions(),question=questions[state.surveyIndex];let value;if(question.textarea)value=$("survey-value").value.trim();else{const selected=[...document.querySelectorAll('#survey-control input:checked')].map(x=>x.value);value=question.multiple?selected:selected[0]}if(!question.optional&&(!value||(Array.isArray(value)&&!value.length))){$("survey-error").hidden=false;return}state.opinion[question.key]=value||null;const refreshed=block.questions();state.surveyIndex++;if(state.surveyIndex<refreshed.length){renderSurvey();return}if(block.next==="data"){show("screen-data",84,"Tus datos");return}state.surveyBlock=block.next;state.surveyIndex=0;renderSurvey()}
function cleanDni(value){return value.replace(/[.\s-]/g,"")}
function apiHeaders(){const key=config.supabaseAnonKey||"",headers={apikey:key,"Content-Type":"application/json"};if(key&&!key.startsWith("sb_"))headers.Authorization=`Bearer ${key}`;return headers}
async function rpc(name,body){const response=await fetch(`${config.supabaseUrl.replace(/\/$/,"")}/rest/v1/rpc/${name}`,{method:"POST",headers:apiHeaders(),body:JSON.stringify(body)});const text=await response.text();if(!response.ok){const error=new Error(text||`HTTP ${response.status}`);error.status=response.status;throw error}try{return JSON.parse(text)}catch{return text}}
function payload(){return{masterclass_slug:state.masterclass.slug,timestamp_inicio:state.started,timestamp_fin:state.finished,edad:state.opinion.edad,genero:state.opinion.genero,pais:state.opinion.pais,formacion:state.opinion.formacion,disciplina:state.opinion.disciplina,anios_docencia:state.opinion.anios_docencia,nivel_educativo:state.opinion.nivel_educativo,sector:state.opinion.sector,conocia_fenomenautas:state.opinion.conocia_fenomenautas,respuestas_eval:state.answers,puntaje:state.score,aprobado:state.score>=5,nombre:state.participant.name,apellido:state.participant.surname,dni:state.participant.dni,mail:state.participant.email,likert_claridad:+state.opinion.likert_claridad,likert_viabilidad:+state.opinion.likert_viabilidad,likert_innovacion:+state.opinion.likert_innovacion,likert_duracion:+state.opinion.likert_duracion,likert_recomendacion:+state.opinion.likert_recomendacion,proy_usar:state.opinion.proy_usar,proy_manera:state.opinion.proy_manera||null,proy_valor:state.opinion.proy_valor,proy_desafios:state.opinion.proy_desafios,proy_enfoque:state.opinion.proy_enfoque,comentario:state.opinion.comentario||null,certificado_generado:false,tiempos_eval:state.times,dispositivo:{tipo:/Mobi|Android/i.test(navigator.userAgent)?"mobile":"desktop",input:matchMedia("(pointer:coarse)").matches?"touch":"mouse",ancho:innerWidth,alto:innerHeight},descargo_pdf:false,descargo_imagen:false}}
async function saveResponse(){if(["localhost","127.0.0.1"].includes(location.hostname))return"00000000-0000-0000-0000-000000000001";if(!config.supabaseUrl||!config.supabaseAnonKey)throw new Error("missing-config");let lastError;for(let attempt=0;attempt<2;attempt++){try{return await rpc("guardar_respuesta",{p_datos:payload()})}catch(error){lastError=error;if(error.status===409||/duplicate|unique|ya existe/i.test(error.message))throw error;if(attempt===0)await new Promise(resolve=>setTimeout(resolve,500))}}throw lastError}
async function submitData(event){event.preventDefault();const form=$("data-form"),error=$("form-error"),button=$("data-submit");error.hidden=true;if(!form.reportValidity())return;const dni=cleanDni($("participant-dni").value.trim());if(!/^\d{7,8}$/.test(dni)){error.textContent="El DNI debe tener 7 u 8 números.";error.hidden=false;return}state.participant={name:$("participant-name").value.trim(),surname:$("participant-surname").value.trim(),dni,email:$("participant-email").value.trim().toLowerCase()};state.finished=new Date().toISOString();button.disabled=true;button.innerHTML='<span class="spinner"></span> Buscando…';try{state.responseId=await saveResponse();showSaved();showResult()}catch(exception){console.error("Supabase save failed",exception);error.textContent=/duplicate|unique|ya existe/i.test(exception.message)?"Ya existe una respuesta para este DNI o correo en esta masterclass.":"No pudimos registrar tus respuestas en este momento. Por favor, esperá unos segundos e intentá nuevamente.";error.hidden=false}finally{button.disabled=false;button.textContent="Buscar mi certificado →"}}
function showSaved(){const indicator=$("save-indicator");indicator.classList.add("show");setTimeout(()=>indicator.classList.remove("show"),1800)}
function showResult(){const approved=state.score>=5,circle=$("score-circle");circle.className=`score-circle ${approved?"approved":"failed"}`;$("result-score").textContent=state.score;$("result-title").textContent=approved?"🎉 ¡Felicitaciones, aprendiste bastante!":"📚 Completaste la evaluación";const scored=state.answers.filter(x=>x.scored);$("answer-review").innerHTML=`<div class="review-summary">Estas son las preguntas, con sus explicaciones correctas:</div>${scored.map((answer,index)=>{const question=state.masterclass.questions.find(q=>q.number===answer.number),correctText=question?.options.find(o=>o.key===question.correct)?.text||"";return `<div class="review-item"><span class="review-icon">${answer.isCorrect?"✅":"❌"}</span><div><div class="review-question">${index+1}. ${esc(answer.prompt)}</div>${answer.isCorrect?`<div class="review-answer good">Correcta · ${esc(answer.selectedText)}</div>`:`<div class="review-answer bad">Tu respuesta: ${esc(answer.selectedText)}</div><div class="review-answer good">Correcta: ${esc(correctText)}</div>`}<div class="review-explanation">${esc(answer.feedback||"")}</div></div></div>`}).join("")}`;show("screen-result",94,"Tus resultados")}
async function markTracking(data){if(!state.responseId||["localhost","127.0.0.1"].includes(location.hostname))return;try{await rpc("guardar_bloque",{p_id:state.responseId,p_datos:data});showSaved()}catch(error){console.error("Tracking save failed",error)}}
function showCertificate(){const approved=state.score>=5;$("certificate-banner").textContent=approved?"CERTIFICADO DE APROBACIÓN":"CERTIFICADO DE PARTICIPACIÓN";$("certificate-phrase").textContent=approved?"aprobó la instancia de formación docente":"participó en la instancia de formación docente";$("certificate-name").textContent=`${state.participant.name} ${state.participant.surname}`;$("certificate-course").textContent=state.masterclass.title;$("certificate-date").textContent=new Date().toLocaleDateString("es-AR",{day:"numeric",month:"long",year:"numeric"});state.certificateCanvas=null;show("screen-certificate",100,"Certificado");markTracking({certificado_generado:true})}
async function certificateCanvas(){if(state.certificateCanvas)return state.certificateCanvas;if(!window.html2canvas)throw new Error("html2canvas");const source=$("certificate"),clone=source.cloneNode(true),sandbox=document.createElement("div");sandbox.style.cssText="position:fixed;left:-10000px;top:0;width:800px;background:#fdf9ef;";clone.style.cssText="width:800px;margin:0;";sandbox.appendChild(clone);document.body.appendChild(sandbox);try{await document.fonts?.ready;await Promise.all([...clone.querySelectorAll("img")].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=img.onerror=resolve})));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));state.certificateCanvas=await html2canvas(clone,{scale:2,backgroundColor:"#fdf9ef",useCORS:true,width:800,height:clone.scrollHeight,windowWidth:900,windowHeight:clone.scrollHeight});return state.certificateCanvas}finally{sandbox.remove()}}
async function downloadPng(){const button=$("download-png"),original=button.innerHTML;button.disabled=true;button.textContent="Preparando imagen…";try{const canvas=await certificateCanvas(),link=document.createElement("a");link.download=`certificado_${state.participant.surname.toLowerCase()}.png`;link.href=canvas.toDataURL("image/png");link.click();markTracking({descargo_imagen:true})}finally{button.disabled=false;button.innerHTML=original}}
async function downloadPdf(){const button=$("download-pdf"),original=button.innerHTML;button.disabled=true;button.textContent="Generando PDF…";try{const canvas=await certificateCanvas(),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"}),pageWidth=pdf.internal.pageSize.getWidth(),pageHeight=pdf.internal.pageSize.getHeight(),ratio=canvas.width/canvas.height;let width=pageWidth-40,height=width/ratio;if(height>pageHeight-40){height=pageHeight-40;width=height*ratio}pdf.addImage(canvas.toDataURL("image/png"),"PNG",(pageWidth-width)/2,(pageHeight-height)/2,width,height);pdf.save(`certificado_${state.participant.surname.toLowerCase()}.pdf`);markTracking({descargo_pdf:true})}finally{button.disabled=false;button.innerHTML=original}}
$("intro-next").onclick=()=>show("screen-eval-intro",3,"Veamos cuánto aprendiste");$("eval-start").onclick=startQuiz;$("question-next").onclick=nextQuestion;$("survey-start").onclick=startSurvey;$("survey-form").onsubmit=submitSurvey;$("data-form").onsubmit=submitData;$("certificate-show").onclick=showCertificate;$("download-png").onclick=downloadPng;$("download-pdf").onclick=downloadPdf;initialize();
})();
