/* EDITABLE: copia textual de los bloques del formulario Fenomenautas original. */
window.OPINION_CONTENT = {
  demographics: [
    {key:"edad",title:"Para conocerte mejor, ¿cuál es tu rango de edad?",options:["Menos de 25 años","25 a 34 años","35 a 44 años","45 a 54 años","55 años o más"]},
    {key:"genero",title:"Género",options:["Femenino","Masculino","No binario / Otro","Prefiero no decirlo"]},
    {key:"pais",title:"País de residencia",options:["Argentina","Bolivia","Brasil","Chile","Colombia","Ecuador","México","Panamá","Paraguay","Perú","Uruguay","Venezuela","España","Otro"]},
    {key:"formacion",title:"¿Cuál es tu título o formación principal?",options:["Maestro/a","Profesor/a","Estudiante de profesorado o de carrera científica","Licenciado/a, científico/a o profesional afín","No soy docente","Otra"]},
    {key:"disciplina",title:"¿En qué área enseñás principalmente?",options:["Ciencias naturales (incluye biológicas, físicas y químicas, entre otras)","Ciencias sociales","Lengua","Matemáticas","Otras","No ejerzo"]},
    {key:"anios_docencia",title:"Años de antigüedad en la docencia",options:["Menos de 2 años","Entre 2 y 5 años","Entre 6 y 10 años","Entre 11 y 20 años","Más de 20 años","Nunca ejercí","Ya estoy jubilada/o"]},
    {key:"nivel_educativo",title:"¿En qué nivel educativo te desempeñás principalmente?",multiple:true,exclusive:["Nunca ejercí","Ya estoy jubilada/o"],options:["Nivel Inicial","Nivel Primario","Nivel Secundario","Nivel Superior / Terciario / Universidad","Nunca ejercí","Ya estoy jubilada/o"]},
    {key:"sector",title:"¿En qué sector del sistema educativo trabajás actualmente?",options:["Exclusivamente en gestión pública / estatal","Exclusivamente en gestión privada","En ambos sectores (público y privado)","No ejerzo"]},
    {key:"conocia_fenomenautas",title:"¿Conocías la plataforma Fenomenautas antes de este video/seminario?",options:["No, es la primera vez que escucho hablar de ella.","Sí, la conocía de nombre pero nunca había explorado sus recursos.","Sí, la conozco y he utilizado alguna secuencia didáctica de forma esporádica.","Sí, la conozco y utilizo frecuentemente sus recursos en mis clases."]}
  ],
  likert: [
    {key:"likert_claridad",title:"<strong>Claridad.</strong> Las explicaciones teóricas y los conceptos abordados fueron claros y fáciles de seguir.",likert:true},
    {key:"likert_viabilidad",title:"<strong>Viabilidad.</strong> Los experimentos o actividades propuestas son viables para llevar a cabo en mi contexto escolar (materiales, espacio, etc.).",likert:true},
    {key:"likert_innovacion",title:"<strong>Innovación.</strong> La propuesta me aportó ideas nuevas o diferentes a las que suelo usar en mis clases.",likert:true},
    {key:"likert_duracion",title:"<strong>Duración.</strong> La duración y el ritmo del video fueron adecuados.",likert:true},
    {key:"likert_recomendacion",title:"<strong>Recomendación.</strong> Le recomendaría este material a otros colegas docentes.",likert:true}
  ],
  projection: [
    {key:"proy_usar",title:"¿Considerás que vas a utilizar o adaptar el material presentado en esta clase en tus prácticas docentes?",options:["Sí, definitivamente lo voy a incorporar a corto plazo.","Sí, es probable que lo sume más adelante en el ciclo lectivo.","Tal vez, tendría que analizar más detalladamente cómo adaptarlo a mi aula.","No creo, no se ajusta a las necesidades actuales de mis cursos."]},
    {key:"proy_manera",title:"Si tu respuesta anterior fue positiva, ¿de qué manera proyectás integrar este material en tu planificación?",multiple:true,conditional:true,options:["Como actividad disparadora o introducción a un tema (partiendo del fenómeno).","Como el núcleo de una secuencia didáctica completa de indagación.","Como material complementario o de profundización para los estudiantes.","Como recurso para instancias de evaluación formativa o proyectos escolares.","Principalmente como inspiración para mi propia formación, no para llevar directo al aula."]},
    {key:"proy_valor",title:"Desde una perspectiva pedagógica, ¿cuál considerás que es el principal valor de este material para tus estudiantes?",options:["Poner a los estudiantes en un rol activo y protagónico frente a la ciencia.","Desarrollar habilidades de pensamiento científico y espíritu crítico.","Ofrecer actividades experimentales de fácil implementación con recursos sencillos.","Vincular los conceptos abstractos de la ciencia escolar con la vida cotidiana.","No considero que tenga valor","No sé"]},
    {key:"proy_desafios",title:"¿Qué tipo de desafíos anticipás para poder implementar este enfoque basado en fenómenos en tu aula?",multiple:true,options:["La falta de tiempo dentro de la carga horaria curricular obligatoria.","La escasez de recursos materiales o infraestructura en la escuela.","La resistencia o falta de costumbre de los estudiantes hacia metodologías activas.","La necesidad de contar con un mayor acompañamiento o capacitación didáctica previa.","No anticipo grandes dificultades, veo muy viable su aplicación.","Otros","No sé"]},
    {key:"proy_enfoque",title:"¿Con qué enfoque metodológico prioritario en tu institución sentís que se alinea mejor esta propuesta?",options:["Aprendizaje Basado en Proyectos (ABP) o Problemas.","Enseñanza por Indagación / STEM.","Modelo clásico expositivo (como ilustración o ejemplo práctico).","Ninguno en particular, se adapta de forma independiente.","Otros","No sé"]}
  ],
  comment:{key:"comentario",title:"Para terminar, ¿tenés algún comentario, sugerencia o idea que quieras compartir con el equipo de Fenomenautas?",placeholder:"Podés comentarnos sobre esta clase en particular, las dificultades que encontrás habitualmente en el aula, o sugerir qué otras temáticas científicas te gustaría que abordemos en el futuro.",textarea:true,optional:true}
};
